#!/bin/bash

echo "📋 Instructions to update Lambda with correct Supabase credentials"
echo "=================================================="
echo ""
echo "1. First, get your LOCAL Supabase service role key:"
echo "   It's already in your environment: $SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "2. Run this command to update the Lambda function:"
echo ""
echo "aws lambda update-function-configuration \\"
echo "  --function-name iwishbag-process-incoming-email \\"
echo "  --environment Variables=\"{SUPABASE_URL='http://127.0.0.1:54321',SUPABASE_SERVICE_ROLE_KEY='$SUPABASE_SERVICE_ROLE_KEY'}\""
echo ""
echo "3. For PRODUCTION, you need to:"
echo "   - Go to: https://supabase.com/dashboard/project/grgvlrvywsfmnmkxrecd/settings/api"
echo "   - Get the service_role key (starts with eyJ...)"
echo "   - Run the command with production URL and key"
echo ""
echo "Current Lambda is configured for production but needs the correct service role key."