name = "iwishbag-edge-api"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "IWISHBAG_CACHE"
id = "6f5087b9d89146dfbeb8efa92a9b4756"

[[d1_databases]]
binding = "DB"
database_name = "iwishbag-edge-cache"
database_id = "3c663e4c-cad7-4262-a73d-f1ec9a4367a9"

[vars]
SYNC_API_KEY = "iwishbag-d1-sync-2024"