name: Test Quote Automation Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Required Secrets
      run: |
        echo "## Checking Required Secrets for Quote Automation" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Check SUPABASE_URL
        if [ -n "${{ secrets.SUPABASE_URL }}" ]; then
          echo "✅ SUPABASE_URL is set" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ SUPABASE_URL is NOT set" >> $GITHUB_STEP_SUMMARY
          echo "   Try using VITE_SUPABASE_URL if available" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Check SUPABASE_SERVICE_ROLE_KEY
        if [ -n "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ]; then
          echo "✅ SUPABASE_SERVICE_ROLE_KEY is set" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ SUPABASE_SERVICE_ROLE_KEY is NOT set" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Check PUBLIC_SITE_URL
        if [ -n "${{ secrets.PUBLIC_SITE_URL }}" ]; then
          echo "✅ PUBLIC_SITE_URL is set" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ PUBLIC_SITE_URL is NOT set" >> $GITHUB_STEP_SUMMARY
          echo "   This should be your production URL (e.g., https://iwishbag.com)" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Check EMAIL_API_KEY
        if [ -n "${{ secrets.EMAIL_API_KEY }}" ]; then
          echo "✅ EMAIL_API_KEY is set" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ EMAIL_API_KEY is NOT set (optional - emails will be logged instead)" >> $GITHUB_STEP_SUMMARY
        fi
        
        # Check alternative VITE_SUPABASE_URL
        if [ -n "${{ secrets.VITE_SUPABASE_URL }}" ]; then
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ℹ️ Note: VITE_SUPABASE_URL is available as alternative" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Next Steps:" >> $GITHUB_STEP_SUMMARY
        echo "1. Add any missing secrets in Settings → Secrets → Actions" >> $GITHUB_STEP_SUMMARY
        echo "2. Run quote automation workflows manually to test" >> $GITHUB_STEP_SUMMARY